
name: upload package to pypi

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: '0.5.5'
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Generate artifact attestation for sdist and wheels
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: "dist/*"

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # TODO: we want this on
        # URL-based dependencies aren't supported
        # https://github.com/atopile/atopile/blob/28b85da0cd29a6743f8f4b5de54ecd1474872b2f/pyproject.toml#L34
        attestations: false
